sudo: required

services:
    - docker

script:
    - cp -a .git/ backend/.git
    - docker-compose run backend sh -c "coverage run -m unittest && coverage xml --include='*/src/*' && python-codacy-coverage -r coverage.xml"
    - cp -a .git/ frontend/.git
    - docker-compose run frontend npm run test-with-coverage

notifications:
    email: false
